import pandas as pd

TOURNEY_RES_TO_KENPOM_TEAM_NAME_MAP = {
    "Albany (NY)": "Albany",
    "Arizona State": "Arizona St.",
    "Arkansas-Pine Bluff": "Arkansas Pine Bluff",
    "Cleveland State": "Cleveland St.",
    "Colorado State": "Colorado St.",
    "Florida State": "Florida St.",
    "Georgia State": "Georgia St.",
    "Iowa State": "Iowa St.",
    "Kansas State": "Kansas St.",
    "Kent State": "Kent St.",
    "Little Rock": "Arkansas Little Rock",
    "Loyola (IL)": "Loyola Chicago",
    "Miami (FL)": "Miami FL",
    "Michigan State": "Michigan St.",
    "Mississippi State": "Mississippi St.",
    "Morehead State": "Morehead St.",
    "Murray State": "Murray St.",
    "NC State": "N.C. State",
    "Norfolk State": "Norfolk St.",
    "North Dakota State": "North Dakota St.",
    "Northwestern State": "Northwestern St.",
    "Ohio State": "Ohio St.",
    "Oklahoma State": "Oklahoma St.",
    "Ole Miss": "Mississippi",
    "Oregon State": "Oregon St.",
    "Pitt": "Pittsburgh",
    "San Diego State": "San Diego St.",
    "St. Joseph's": "Saint Joseph's",
    "UC-Davis": "UC Davis",
    "UC-Irvine": "UC Irvine",
    "UConn": "Connecticut",
    "UNC": "North Carolina",
    "Washington State": "Washington St.",
    "Wichita State": "Wichita St.",
}

TOURNEY_RES_TO_TEAM_STATS_TEAM_NAME_MAP = {
    "Abilene Christian": "Abilene Christian Wildcats",
    "Air Force": "Air Force Falcons",
    "Akron": "Akron Zips",
    "Alabama State": "Alabama State Hornets",
    "Albany (NY)": "Albany (NY) Great Danes",
    "American": "American Eagles",
    "Appalachian State": "Appalachian State Mountaineers",
    "Arizona State": "Arizona State Sun Devils",
    "Arkansas-Pine Bluff": "Arkansas-Pine Bluff Golden Lions",
    "Auburn": "Auburn Tigers",
    "Austin Peay": "Austin Peay Governors",
    "BYU": "BYU Cougars",
    "Baylor": "Baylor Bears",
    "Belmont": "Belmont Bruins",
    "Binghamton": "Binghamton Bearcats",
    "Boise State": "Boise State Broncos",
    "Boston College": "Boston College Eagles",
    "Boston University": "Boston University Terriers",
    "Bradley": "Bradley Braves",
    "Bucknell": "Bucknell Bison",
    "Butler": "Butler Bulldogs",
    "Cal Poly": "Cal Poly Mustangs",
    "Cal State Bakersfield": "Cal State Bakersfield Roadrunners",
    "Cal State Fullerton": "Cal State Fullerton Titans",
    "Cal State Northridge": "Cal State Northridge Matadors",
    "California": "California Golden Bears",
    "Central Connecticut": "Central Connecticut Blue Devils",
    "Central Michigan": "Central Michigan Chippewas",
    "Charlotte": "Charlotte 49ers",
    "Chattanooga": "Chattanooga Mocs",
    "Cincinnati": "Cincinnati Bearcats",
    "Clemson": "Clemson Tigers",
    "Cleveland State": "Cleveland State Vikings",
    "Colgate": "Colgate Raiders",
    "College of Charleston": "College of Charleston Cougars",
    "Colorado State": "Colorado State Rams",
    "Cornell": "Cornell Big Red",
    "Creighton": "Creighton Bluejays",
    "Davidson": "Davidson Wildcats",
    "Dayton": "Dayton Flyers",
    "DePaul": "DePaul Blue Demons",
    "Delaware": "Delaware State Hornets",
    "Delaware State": "Delaware State Hornets",
    "Drake": "Drake Bulldogs",
    "Drexel": "Drexel Dragons",
    "ETSU": "ETSU Buccaneers",
    "Eastern Kentucky": "Eastern Kentucky Colonels",
    "Eastern Washington": "Eastern Washington Eagles",
    "Fairleigh Dickinson": "Fairleigh Dickinson Knights",
    "Florida A&M": "Florida A&M Rattlers",
    "Florida Atlantic": "Florida Atlantic Owls",
    "Florida Gulf Coast": "Florida Gulf Coast Eagles",
    "Florida State": "Florida State Seminoles",
    "Fresno State": "Fresno State Bulldogs",
    "Gardner-Webb": "Gardner-Webb Runnin' Bulldogs",
    "George Mason": "George Mason Patriots",
    "George Washington": "George Washington Colonials",
    "Georgetown": "Georgetown Hoyas",
    "Georgia State": "Georgia State Panthers",
    "Georgia Tech": "Georgia Tech Yellow Jackets",
    "Gonzaga": "Gonzaga Bulldogs",
    "Grand Canyon": "Grand Canyon Antelopes",
    "Green Bay": "Green Bay Phoenix",
    "Hampton": "Hampton Pirates",
    "Hartford": "Hartford Hawks",
    "Hawaii": "Hawaii Rainbow Warriors",
    "Holy Cross": "Holy Cross Crusaders",
    "IUPUI": "IUPUI Jaguars",
    "Indiana": "Indiana Hoosiers",
    "Iona": "Iona Gaels",
    "Iowa State": "Iowa State Cyclones",
    "Jackson State": "Jackson State Tigers",
    "Jacksonville State": "Jacksonville State Gamecocks",
    "James Madison": "James Madison Dukes",
    "Kansas State": "Kansas State Wildcats",
    "Kent State": "Kent State Golden Flashes",
    "LIU": "LIU Sharks",
    "LSU": "LSU Fighting Tigers",
    "La Salle": "La Salle Explorers",
    "Lamar": "Lamar Cardinals",
    "Lehigh": "Lehigh Mountain Hawks",
    "Liberty": "Liberty Flames",
    "Lipscomb": "Lipscomb Bisons",
    "Little Rock": "Little Rock Trojans",
    "Long Beach State": "Long Beach State 49ers",
    "Louisville": "Louisville Cardinals",
    "Loyola (IL)": "Loyola (IL) Ramblers",
    "Manhattan": "Manhattan Jaspers",
    "Marquette": "Marquette Golden Eagles",
    "Marshall": "Marshall Thundering Herd",
    "Maryland": "Maryland Terrapins",
    "McNeese State": "McNeese State Cowboys",
    "Memphis": "Memphis Tigers",
    "Miami (FL)": "Miami (FL) Hurricanes",
    "Miami (OH)": "Miami (OH) RedHawks",
    "Michigan State": "Michigan State Spartans",
    "Middle Tennessee": "Middle Tennessee Blue Raiders",
    "Milwaukee": "Milwaukee Panthers",
    "Minnesota": "Minnesota Golden Gophers",
    "Mississippi State": "Mississippi State Bulldogs",
    "Mississippi Valley State": "Mississippi Valley State Delta Devils",
    "Missouri": "Missouri Tigers",
    "Monmouth": "Monmouth Hawks",
    "Montana": "Montana Grizzlies",
    "Morehead State": "Morehead State Eagles",
    "Morgan State": "Morgan State Bears",
    "Mount St. Mary's": "Mount St. Mary's Mountaineers",
    "Murray State": "Murray State Racers",
    "NC State": "NC State Wolfpack",
    "Nevada": "Nevada Wolf Pack",
    "New Mexico State": "New Mexico State Aggies",
    "New Orleans": "New Orleans Privateers",
    "Niagara": "Niagara Purple Eagles",
    "Norfolk State": "Norfolk State Spartans",
    "North Carolina A&T": "North Carolina A&T Aggies",
    "North Carolina Central": "North Carolina Central Eagles",
    "North Dakota State": "North Dakota State Bison",
    "North Florida": "North Florida Ospreys",
    "North Texas": "North Texas Mean Green",
    "Northeastern": "Northeastern Huskies",
    "Northern Iowa": "Northern Iowa Panthers",
    "Northern Kentucky": "Northern Kentucky Norse",
    "Northwestern State": "Northwestern State Demons",
    "Notre Dame": "Notre Dame Fighting Irish",
    "Oakland": "Oakland Golden Grizzlies",
    "Ohio State": "Ohio State Buckeyes",
    "Oklahoma State": "Oklahoma State Cowboys",
    "Old Dominion": "Old Dominion Monarchs",
    "Ole Miss": "Ole Miss Rebels",
    "Oral Roberts": "Oral Roberts Golden Eagles",
    "Oregon State": "Oregon State Beavers",
    "Pacific": "Pacific Tigers",
    "Penn": "Penn Quakers",
    "Pepperdine": "Pepperdine Waves",
    "Pitt": "Pitt Panthers",
    "Portland State": "Portland State Vikings",
    "Prairie View": "Prairie View Panthers",
    "Princeton": "Princeton Tigers",
    "Providence": "Providence Friars",
    "Purdue": "Purdue Boilermakers",
    "Radford": "Radford Highlanders",
    "Rhode Island": "Rhode Island Rams",
    "Richmond": "Richmond Spiders",
    "Robert Morris": "Robert Morris Colonials",
    "Rutgers": "Rutgers Scarlet Knights",
    "SMU": "SMU Mustangs",
    "Saint Louis": "Saint Louis Billikens",
    "Saint Mary's": "Saint Mary's Gaels",
    "Sam Houston State": "Sam Houston State Bearkats",
    "San Diego State": "San Diego State Aztecs",
    "Seton Hall": "Seton Hall Pirates",
    "Siena": "Siena Saints",
    "South Alabama": "South Alabama Jaguars",
    "South Carolina State": "South Carolina State Bulldogs",
    "South Dakota State": "South Dakota State Jackrabbits",
    "South Florida": "South Florida Bulls",
    "Southeastern Louisiana": "Southeastern Louisiana Lions",
    "Southern Illinois": "Southern Illinois Salukis",
    "St. Bonaventure": "St. Bonaventure Bonnies",
    "St. John's (NY)": "St. John's (NY) Red Storm",
    "St. Joseph's": "St. Joseph's Hawks",
    "Stanford": "Stanford Cardinal",
    "Stephen F. Austin": "Stephen F. Austin Lumberjacks",
    "Stony Brook": "Stony Brook Seawolves",
    "Syracuse": "Syracuse Orange",
    "TCU": "TCU Horned Frogs",
    "Temple": "Temple Owls",
    "Texas A&M-Corpus Christi": "Texas A&M-Corpus Christi Islanders",
    "Texas Southern": "Texas Southern Tigers",
    "Texas Tech": "Texas Tech Red Raiders",
    "Troy": "Troy Trojans",
    "Tulsa": "Tulsa Golden Hurricane",
    "UAB": "UAB Blazers",
    "UC-Davis": "UC-Davis Aggies",
    "UC-Irvine": "UC-Irvine Anteaters",
    "UCF": "UCF Knights",
    "UCLA": "UCLA Bruins",
    "UCSB": "UCSB Gauchos",
    "UConn": "UConn Huskies",
    "UIC": "UIC Flames",
    "UMBC": "UMBC Retrievers",
    "UNC Asheville": "UNC Asheville Bulldogs",
    "UNC Greensboro": "UNC Greensboro Spartans",
    "UNC Wilmington": "UNC Wilmington Seahawks",
    "UNLV": "UNLV Rebels",
    "USC": "USC Trojans",
    "UT Arlington": "UT Arlington Mavericks",
    "UTEP": "UTEP Miners",
    "UTSA": "UTSA Roadrunners",
    "Utah State": "Utah State Aggies",
    "VCU": "VCU Rams",
    "Valparaiso": "Valparaiso Beacons",
    "Vanderbilt": "Vanderbilt Commodores",
    "Vermont": "Vermont Catamounts",
    "Villanova": "Villanova Wildcats",
    "Virginia Tech": "Virginia Tech Hokies",
    "Wagner": "Wagner Seahawks",
    "Wake Forest": "Wake Forest Demon Deacons",
    "Washington State": "Washington State Cougars",
    "Weber State": "Weber State Wildcats",
    "West Virginia": "West Virginia Mountaineers",
    "Western Kentucky": "Western Kentucky Hilltoppers",
    "Western Michigan": "Western Michigan Broncos",
    "Wichita State": "Wichita State Shockers",
    "Winthrop": "Winthrop Eagles",
    "Wisconsin": "Wisconsin Badgers",
    "Wofford": "Wofford Terriers",
    "Wright State": "Wright State Raiders",
    "Wyoming": "Wyoming Cowboys",
    "Xavier": "Xavier Musketeers",
    "Yale": "Yale Bulldogs",
    # Manual
    "Alabama": "Alabama Crimson Tide",
    "Arizona": "Arizona Wildcats",
    "Arkansas": "Arkansas Razorbacks",
    "Buffalo": "Buffalo Bulls",
    "Colorado": "Colorado Buffaloes",
    "Duke": "Duke Blue Devils",
    "Florida": "Florida Gators",
    "Georgia": "Georgia Bulldogs",
    # "Harvard",# TODO: no harvard?
    "Houston": "Houston Cougars",
    "Illinois": "Illinois Fighting Illini",
    "Iowa": "Iowa Hawkeyes",
    "Kentucky": "Kentucky Wildcats",
    # "Mercer", # TODO: no mercer?
    "Michigan": "Michigan Wolverines",
    "New Mexico": "New Mexico Lobos",
    "Northwestern": "Northwestern Wildcats",
    "Ohio": "Ohio Bobcats",
    "Oklahoma": "Oklahoma Sooners",
    "Oregon": "Oregon Ducks",
    "San Diego": "San Diego Toreros",
    "South Carolina": "South Carolina Gamecocks",
    "Tennessee": "Tennessee Volunteers",
    "Texas": "Texas Longhorns",
    "Texas A&M": "Texas A&M Aggies",
    "UNC": "UNC Tar Heels",
    "Utah": "Utah Utes",
    "Virginia": "Virginia Cavaliers",
    "Washington": "Washington Huskies",
}


def main():
    kenpom = pd.read_csv("data/kenpom-data.csv")
    team_stats = pd.read_csv("data/team-stats.csv")
    tourney_res = pd.read_csv("data/tourney-results.csv")

    kenpom["Team"] = kenpom.Team.replace(
        {v: k for k, v in TOURNEY_RES_TO_KENPOM_TEAM_NAME_MAP.items()}
    )
    team_stats["Team"] = team_stats.Team.replace(
        {v: k for k, v in TOURNEY_RES_TO_TEAM_STATS_TEAM_NAME_MAP.items()}
    )

    tourney_res_kenpom_win = pd.merge(
        tourney_res,
        kenpom.rename(
            columns=lambda c: f"Winning{c}" if c not in {"Year", "Team"} else c
        ),
        how="left",
        left_on=["Year", "WinningTeam"],
        right_on=["Year", "Team"],
    )
    tourney_res_kenpom = pd.merge(
        tourney_res_kenpom_win,
        kenpom.rename(
            columns=lambda c: f"Losing{c}" if c not in {"Year", "Team"} else c
        ),
        how="left",
        left_on=["Year", "LosingTeam"],
        right_on=["Year", "Team"],
    )

    tourney_res_kenpom_team_stats_win = pd.merge(
        tourney_res_kenpom,
        team_stats.rename(
            columns=lambda c: f"Winning_{c}" if c not in {"Year", "Team"} else c
        ),
        how="left",
        left_on=["Year", "WinningTeam"],
        right_on=["Year", "Team"],
    )

    tourney_res_kenpom_team_stats = pd.merge(
        tourney_res_kenpom_team_stats_win,
        team_stats.rename(
            columns=lambda c: f"Losing_{c}" if c not in {"Year", "Team"} else c
        ),
        how="left",
        left_on=["Year", "LosingTeam"],
        right_on=["Year", "Team"],
    )

    tourney_res_kenpom_team_stats.to_csv("data/merged.csv", index=False)


if __name__ == "__main__":
    main()
